[package]
name = "chipbox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.5.16", features = ["derive"] }
clap_complete = "^4.5.18"
serde = { version = "1.0.208", features = ["derive"] }
serde_yaml = "0.9.34"
