name: Create/update tag
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      run-id:
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ github.event.inputs.version}}
          git push origin ${{ github.event.inputs.version}}
          echo "push tag ${{ github.event.inputs.version}}"

      - uses: actions/download-artifact@v4
        with:
          name: chipbox
          path: target/x86_64-unknown-linux-musl/release/chipbox
          run-id: ${{ github.event.inputs.run-id}}

      - name: Release
        uses: softprops/action-gh-release@v2
        # if: github.ref_type == 'tag'
        with:
          name: "${{ github.event.inputs.version}}"
          tag_name: "${{ github.event.inputs.version}}"
          files: target/x86_64-unknown-linux-musl/release/chipbox
