name: Create/update tag
on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ github.event.inputs.version}}
          git push origin ${{ github.event.inputs.version}}
          echo "push tag ${{ github.event.inputs.version}}"
